### ISSUE TITLE
Variant limited by quantity

### ISSUE THREAD

**Issue by 4n70w4** [markphelps/flipt#184]
Hi! Thanks for the flipt!

I have a need to give specific variant in a limited quantity, for example, 1000.

I would also like to do 2 distribution strategies:

1) start distributing the variant to everyone with the highest priority until quantity ends.

2) evenly adding for a certain time, but not more than a given quantity.

**Comment by markphelps** [comment]
Hi @4n70w4! Thanks for the feature request

Would you mind giving a more concrete description on how you would like this to work? Perhaps with some example flags/segments/rules and evaluation requests?

Pseudo code or diagrams would be great so that I can visualize this potential feature!

**Comment by 4n70w4** [comment]
Example 1: show special message for first 1 000 non registered visitors.

![image](https://user-images.githubusercontent.com/38257723/69492466-40115000-0eb4-11ea-8317-6ebee3ca4632.png)

It would be nice to have a field for a quantity limit.

Example 2: the same but also random distribution limited by time

![image](https://user-images.githubusercontent.com/38257723/69492533-1c9ad500-0eb5-11ea-9c06-c1b09e0043a1.png)

Perhaps it is better that the limits on the quantity and date are attributes of the variant, instead attributes of targeting rule.

Example 3: distribute variant no more than 1 time in 5 minutes

![image](https://user-images.githubusercontent.com/38257723/69492607-eca00180-0eb5-11ea-932e-0d74b1d8f8cf.png)

**Comment by markphelps** [comment]
@4n70w4 thanks again for the feature request. I think you should be able to accomplish most of what you want (**ex 1** and **ex 2**) by using segment constraints and rules instead of requiring these additions to variants.

Example segment:

<img width="1136" alt="Screen Shot 2019-11-25 at 2 25 57 PM" src="https://user-images.githubusercontent.com/209477/69571213-88517080-0f8f-11ea-9cbe-457c31c74e77.png">

Then your rule could require this segment to match, and your evaluation request would contain the information required to see if this is a match:

```json
{
    "flagKey": "adsf",
    "entityId": "429a53d6-ec98-43a1-b7c9-9e04be9e3eec",
    "context": {
        "priority": "1",
        "unix_time": "1574709034"
    }
}
```

As for **ex 3**, I dont think Flipt will likely implement this because it would require tracking (and storing) the number of requests which would likely slow down evaluation. I think a better place to implement this logic would be on your applications side.

**Comment by 4n70w4** [comment]
@markphelps thanks! I will try it, but it seems to me that segments will not cover all cases.
