### ISSUE TITLE
Value param not presented in evaluate body after edit percentage rollout

### ISSUE THREAD

**Issue by 4n70w4** [markphelps/flipt#187]
Initial settings:

![image](https://user-images.githubusercontent.com/38257723/69493351-f4b06f00-0ebe-11ea-83e6-8c0952b8e617.png)

I request evaluate:

```json
{
"flag_key": "demo",
"entity_id": "1"
}
```

and gets:

```json
{
  "requestId": "fe7c640a-8715-4a08-87d3-cfdb8d014f6d",
  "entityId": "1",
  "match": true,
  "flagKey": "demo",
  "segmentKey": "non-registered-visitors",
  "timestamp": "2019-11-24T10:33:43.123944900Z",
  "value": "three",
  "requestDurationMillis": 0.262
}
```

Then I modified percentage rollout (set first = 0):

![image](https://user-images.githubusercontent.com/38257723/69493363-1d386900-0ebf-11ea-8606-60d89eae2165.png)

And again request evaluate:

```json
{
"flag_key": "demo",
"entity_id": "1"
}
```

and gets:

```json
{
  "requestId": "dc1939ba-081d-40f5-afbe-d8a3c1136d84",
  "entityId": "1",
  "flagKey": "demo",
  "segmentKey": "non-registered-visitors",
  "timestamp": "2019-11-24T10:34:27.103771200Z",
  "requestDurationMillis": 0.293
}
```

Why did the value disappear?

**Comment by 4n70w4** [comment]
This is reproduced only with some entityId. I deleted everything, recreated it and could not reproduce it with the same values.

**Comment by 4n70w4** [comment]
Okay. I found the missing step to reproduce the error.

1) Create variants
2) Create rule with percentage rollout
3) Evalueate few entityId
4) Delete any variant
5) Recreate variant
6) Delete rule with percentage rollout
7) Recreate rule with percentage rollout
8) Evalueane few entityId
9) Change percentage rollout for any variant to 0
10) Evalueane few entityId
11) Get evaluate body without value for random entityId

**Comment by markphelps** [comment]
@4n70w4 The reason that the response does not contain `match` or `variantKey` is because your request likely didnt match any distributions, it likely matched the remaining 34.33% empty space (100% - 33.33% - %33.33%)

Ideally, you should check the `match` value in the response first to determine if this is a valid match.

I could reproduce this by simply setting a variant distribution to 0% and trying a few different `entityId`s:

<img width="398" alt="Screen Shot 2019-11-25 at 1 07 15 PM" src="https://user-images.githubusercontent.com/209477/69566216-9bab0e80-0f84-11ea-935b-5eaefec449a8.png">

```json
{
    "requestId": "6935805f-2267-49f9-82bf-784a06435a3a",
    "entityId": "82e19554-e534-4471-a160-efad701a2270",
    "requestContext": {
        "foo": "bar"
    },
    "flagKey": "adsf",
    "segmentKey": "yo-myname-is-",
    "timestamp": "2019-11-25T17:57:18.445199Z",
    "requestDurationMillis": 1.312333
}
```

If you turn on debug logging be setting the env var `FLIPT_LOG_LEVEL=debug` when running Flipt, you should see something like:

```
DEBU[0079] did not match any distributions               request="request_id:\"6935805f-2267-49f9-82bf-784a06435a3a\" flag_key:\"adsf\" entity_id:\"82e19554-e534-4471-a160-efad701a2270\" context:<key:\"foo\" value:\"bar\" > " server=grpc storage=evaluator
```
In the logs.

Curious as to what would you expect to happen in this case? 

Some possible options I can think of:

1. Do nothing (the current approach), which means the user must set a different entityId to potentially get a valid variant.
1. Flipt should move on to the next rule (if any) and try again

I'm not sure which option is the most intuitive. But at the very least I think I could update the documentation to make this more clear

**Comment by 4n70w4** [comment]
I'll see it a bit later.

Also why not give debug in json reesponse by debug flag? Like this: https://checkr.github.io/flagr/#/flagr_debugging
