### ISSUE TITLE
Clarify 'on' behavior

### ISSUE THREAD

**Issue by dcramer** [markphelps/flipt#263]
It's not obvious to a user what "on" or "off" does. I would assume they fully turn the feature on or off, but at least the for the on state thats not true.

So here's the question:

Should a flag with "on" and no rules be on? If not, then maybe its at least worth clarifying in the user (help text? something else?) what the behavior is.

**Comment by dcramer** [comment]
Similar concern: it's not obvious how entity_id is used in the system. I'm guessing the variants rely on that?

**Comment by dcramer** [comment]
Quick thought: when the state is "on" but no targeting is defined, show a different state + a helper text saying its not active and why?

**Comment by markphelps** [comment]
So you can use flags in two ways:

1. simple on/off with no rules defined, no evaluation, you just wanna toggle something on and off. On or enabled in this case means if you do `GetFlag`, the enabled field will return true, and you can use that in your application as you'd like
2. flags with rules will only `Evaluate` if the Flag is enabled, or 'on'

I agree I think I could call this out better in the docs. Will do!

Re entityID you're right, its required to figure out which 'bucket' your evaluation request falls into so that it can reliably return the same variant for that request each time:

https://flipt.io/docs/concepts/#entities

> For Flipt to successfully determine which bucket your entities fall into, it must have a way to uniquely identify them. This is the entityId and it is a simple string. It's up to you what that entityId is.
