### ISSUE TITLE
The "Try It" section implies "0.0.0.0" means "localhost"

### ISSUE THREAD

**Issue by edumucelli** [markphelps/flipt#385]
When giving it a try on Flipt and reading the documentation it took me a while to see that the service does not runs on `localhost` by default, but on `0.0.0.0`. They are not the same thing and can have very different meanings, roughly speaking one is the loopback interface, while the other respond to all interfaces.

The current README states:

```
Try Flipt out yourself with Docker:

❯ docker run --rm -p 8080:8080 -p 9000:9000 -t markphelps/flipt:latest

Flipt UI will now be reachable at http://localhost:8080/.
```

But we can see in the demo GIF that:

```
API: http://0.0.0.0:8080/api/v1
UI: http://0.0.0.0:8080
```

I would suggest either replacing the default host to `127.0.0.1` in `config/default.yml` as it is likely what devs are expecting or changing the documentation to say something in the lines:

`Flipt UI will now be reachable at http://0.0.0.0:8080/` instead of `Flipt UI will now be reachable at http://localhost:8080/`

If that makes sense, I can make a PR if you prefer.

**Comment by markphelps** [comment]
Thanks for the bug report @edumucelli !

I think we could do a two pronged approach:

In the first PR: Change the docs/README to say `0.0.0.0` in the short term

In the second PR:  Change the config/tests/docs/README to be `127.0.0.1` instead of `0.0.0.0`

My reasoning for this two step fix is to:

1. Get the docs to be in line with reality ASAP
2. I agree that devs prob expect it to be reachable at `127.0.0.1`, however I think this change may be slightly more involved and not backwards compatible.. so I'd prefer to open a separate PR for this and merge it right before releasing a new version

What do you think?

**Comment by edumucelli** [comment]
Looks good to me. Can I work on that?

**Comment by markphelps** [comment]
Yes please!

**Comment by markphelps** [comment]
Fixed
