### ISSUE TITLE
How can we help?

### ISSUE THREAD

**Issue by yns01** [markphelps/flipt#59]
Great project. I'd like to contribute, do you have features that you have in mind? If so, it would be great if you can create issues so contributors can jump in.

**Comment by markphelps** [comment]
Hi @yns01! Thanks, I would love some help!

I can think of a few things off the top of my head:

* Supporting additional databases such as Postgres and potentially MySQL. See #41 for more info.
* Better documentation/examples/diagrams around using variants and percentage distributions.
* Rule evaluation caching, this one might be a bit more challenging because of how rule evaluation is [currently done](https://github.com/markphelps/flipt/blob/4dadd3ef0c0dccdda62b8db063fe15c748941f2b/storage/rule.go#L452) and also this will likely change if multiple databases are supported.

I'll write up some proper issues for these this weekend and create a project board/milestone to track.

Thank you again for any help/ideas/anything!

**Comment by markphelps** [comment]
I've created a [project](https://github.com/markphelps/flipt/projects/1) to help track TODOs in Kanban board.

Please feel free to pick off something in the TODO column or use the [help wanted](https://github.com/markphelps/flipt/labels/help%20wanted) label search as well. I'll also add this info to the README.

Thanks again!

**Comment by markphelps** [comment]
FYI here's the section I added to the README: https://github.com/markphelps/flipt/blob/master/README.md#how-to-contribute
